### ISSUE TITLE
DinD: Docker engine not starting

### ISSUE THREAD

**Issue by Miladiir** [vegardit/docker-gitea-act-runner#20]
After starting the container, the docker engine within the container does not seem to start correctly.

docker-compose.yml:
```yaml
version: '3.8'

services:
  gitea_act_runner:
    image: vegardit/gitea-act-runner:dind-rootless-latest
    privileged: true
    volumes:
      - data:/data
    environment:
      TZ: "Europe/Berlin"
      GITEA_INSTANCE_URL: [redacted]
      GITEA_RUNNER_REGISTRATION_TOKEN: [redacted]
      GITEA_RUNNER_NAME: [redacted]
volumes:
  data:
```

Console output:
```
gitea_runner-gitea_act_runner-1  |    _____ _ _                            _     _____
gitea_runner-gitea_act_runner-1  |   / ____(_) |                 /\       | |   |  __ \
gitea_runner-gitea_act_runner-1  |  | |  __ _| |_ ___  __ _     /  \   ___| |_  | |__) |   _ _ __  _ __   ___ _ __
gitea_runner-gitea_act_runner-1  |  | | |_ | | __/ _ \/ _` |   / /\ \ / __| __| |  _  / | | | '_ \| '_ \ / _ \ '__|
gitea_runner-gitea_act_runner-1  |  | |__| | | ||  __/ (_| |  / ____ \ (__| |_  | | \ \ |_| | | | | | | |  __/ |
gitea_runner-gitea_act_runner-1  |   \_____|_|\__\___|\__,_| /_/    \_\___|\__| |_|  \_\__,_|_| |_|_| |_|\___|_|
gitea_runner-gitea_act_runner-1  |
gitea_runner-gitea_act_runner-1  | GIT_REPO:    https://github.com/vegardit/docker-gitea-act-runner
gitea_runner-gitea_act_runner-1  | GIT_BRANCH:  main
gitea_runner-gitea_act_runner-1  | GIT_COMMIT:  0866e7a @ 2023-07-03 17:10:59 UTC
gitea_runner-gitea_act_runner-1  | IMAGE_BUILD: 2023-07-03T17:11:52Z
gitea_runner-gitea_act_runner-1  |
gitea_runner-gitea_act_runner-1  | 2023-07-04 23:35:21 INFO [/opt/run.sh:26] Timezone is CEST +0200
gitea_runner-gitea_act_runner-1  | 2023-07-04 23:35:21 INFO [/opt/run.sh:27] Hostname: 3f504d42d9a3
gitea_runner-gitea_act_runner-1  | 2023-07-04 23:35:21 INFO [/opt/run.sh:28] IP Addresses:
gitea_runner-gitea_act_runner-1  |  - 172.20.0.2
gitea_runner-gitea_act_runner-1  | 2023-07-04 23:35:21 INFO [/opt/run.sh:62] Starting Docker engine...
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/cpuset: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/cpu: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/cpuacct: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/blkio: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/memory: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/devices: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/freezer: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/net_cls: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/perf_event: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/net_prio: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/hugetlb: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/pids: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/rdma: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | mount: /sys/fs/cgroup/misc: permission denied.
gitea_runner-gitea_act_runner-1  |        dmesg(1) may have more information after failed mount system call.
gitea_runner-gitea_act_runner-1  | Starting Docker: docker.
gitea_runner-gitea_act_runner-1  | 2023-07-04 23:35:22 INFO [/opt/run.sh:67] Waiting for Docker engine to start...
gitea_runner-gitea_act_runner-1  | time="2023-07-04T21:35:23.035500635Z" level=info msg="API listen on /var/run/docker.sock"
gitea_runner-gitea_act_runner-1  | 2023-07-04 23:35:24 INFO [/opt/run.sh:67] Waiting for Docker engine to start...
```

The last two lines are repeated endlessly. Any ideas?

**Comment by sebthom** [comment]
Does it only happen for the rootless image version?

**Comment by Miladiir** [comment]
Yep, the others work as expected.

**Comment by JeffersonTerrerfield** [comment]
I have the exact same error. However, for me it does not work with rootless nor rootful DinD image. But I have to add, that I use rootless podman and podman-compose and not docker and docker-compose on my host.

**Comment by sebthom** [comment]
@sinitcin when using dind you cannot mount the docker socket from the host system, i.e. you need to remove this line:
> ```yaml
> - /var/run/docker.sock:/var/run/docker.sock:rw
> ```

**Comment by sebthom** [comment]
@Miladiir the dind-rootless container tried to start docker without the rootless mode, I fixed that. please give it another try.

**Comment by JeffersonTerrerfield** [comment]
I used the vegardit/gitea-act-runner:dind-rootless-latest from Docker Hub. However, I still get the error.

`podman log`:
<details>
  <summary>Output</summary>

GIT_REPO:    https://github.com/vegardit/docker-gitea-act-runner
GIT_BRANCH:  main
GIT_COMMIT:  6b01de7 @ 2023-07-23 11:41:44 UTC
IMAGE_BUILD: 2023-07-23T11:42:28Z

2023-07-23 14:26:31 INFO [/opt/run.sh:26] act_runner version v0.2.3
2023-07-23 14:26:31 INFO [/opt/run.sh:27] Timezone: CEST +0200
2023-07-23 14:26:31 INFO [/opt/run.sh:28] Hostname: 70784b3a707b
2023-07-23 14:26:31 INFO [/opt/run.sh:29] IP Addresses:
 - 10.89.0.3
2023-07-23 14:26:31 INFO [/opt/run.sh:39] Starting Docker engine (rootless)...
2023-07-23 14:26:31 INFO [/opt/run.sh:54] Waiting for Docker engine to start...
: exit status 1
2023-07-23 14:26:33 INFO [/opt/run.sh:54] Waiting for Docker engine to start...
: exit status 1
2023-07-23 14:26:36 INFO [/opt/run.sh:54] Waiting for Docker engine to start...
: exit status 1
..........
</details>

My `docker-compose.yml`:
<details>
  <summary>Content</summary>

version: "3.8"

services:
  server:
    image: gitea/gitea:1.20-rootless
    user: 1001
    restart: always
    volumes:
      - ./data/gitea/data:/var/lib/gitea:Z
      - ./data/gitea/config:/etc/gitea:Z
      - /usr/share/zoneinfo/Europe/Berlin:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"

  gitea_act_runner:
    image: vegardit/gitea-act-runner:dind-rootless-latest
    privileged: true
    volumes:
      - ./data/runner/data:/data:rw,Z
    environment:
      TZ: "Europe/Berlin"
      GITEA_INSTANCE_INSECURE: true
      GITEA_INSTANCE_URL: 'http://localhost:3000'
      GITEA_RUNNER_REGISTRATION_TOKEN: 'XXXXX'
</details>

**Comment by sebthom** [comment]
@JeffersonTerrerfield I am not using podman, the image is targeting the docker runtime. However if you find anything useful to improve podman support, PRs are welcome.

**Comment by Miladiir** [comment]
Works now. Thanks
